### ISSUE TITLE
Please create an example with a module-info.java

### ISSUE THREAD

**Issue by coderextreme** [electronstudio/jaylib-ffm-example-project#1]
For example, here's my module-info.java.

module net.coderextreme {
    requires javafx.controls;
    requires java.desktop;
    requires java.rmi;
    requires com.formdev.flatlaf;
    requires org.seleniumhq.selenium.api;
    requires org.seleniumhq.selenium.support;
    requires org.seleniumhq.selenium.chrome_driver;
    requires org.seleniumhq.selenium.firefox_driver;
    requires org.seleniumhq.selenium.edge_driver;
    requires org.seleniumhq.selenium.safari_driver;
    requires org.seleniumhq.selenium.ie_driver;
    requires org.seleniumhq.selenium.remote_driver;
    opens net.coderextreme.motion to java.rmi;
    exports net.coderextreme.dev;
    exports net.coderextreme.icbm;
    exports net.coderextreme.main;
    exports net.coderextreme.motion;
}

**Comment by electronstudio** [comment]
Jaylib-FFM isn’t a modular jar so I don’t see the point of creating a modular example. If you want to use it in a modular app just use it as an automatic module.

**Comment by electronstudio** [comment]
Example with module-info.java: https://github.com/electronstudio/jaylib-ffm-example-project/tree/modular

**Comment by electronstudio** [comment]
there was a bug, just fixed

**Comment by coderextreme** [comment]
Aye, yep.  Can you give details so we can learn?
